fix incorrect API urls that were there for some reason & issue template descriptions
modrinth/code pull request #1310
Opened 2024-07-21 02:47 UTC by KTrain5169

regarding fixing the incorrect API urls I'm not sure if this would break something but I assume it can just slot right in without issue

2024-07-21 02:50 UTC, blryface commented
oh screw you :(

2024-07-21 03:28 UTC, Prospector requested changes
API routes are not incorrect, please do not change things like that if you don't understand what they're doing and didn't test the changes

2024-07-21 03:38 UTC, KTrain5169 commented
oh the commit doesn't show up

2024-07-31 19:40 UTC, Geometrically approved these changes

2024-07-31 19:45 UTC, merged