Setup Typescript in Theseus
modrinth/code pull request #2286
Opened 2024-08-24 16:35 UTC by ferothefox

2024-08-24 16:39 UTC, brawaru commented
You probably want to include [`vue-tsc`](https://www.npmjs.com/package/vue-tsc) to type check all files including Vue SFCs (the script would be `vue-tsc --noEmit`).

2024-08-24 16:43 UTC, ferothefox commented
> You probably want to include [`vue-tsc`](https://www.npmjs.com/package/vue-tsc) to type check all files including Vue SFCs (the script would be `vue-tsc --noEmit`).

I'll get around to doing this for sure - was mainly focused on getting a dirty setup out real quick.

2024-08-24 19:24 UTC, Geometrically approved these changes

2024-08-26 21:01 UTC, Prospector approved these changes

2024-08-26 21:06 UTC, Prospector approved these changes

2024-08-27 10:13 UTC, brawaru requested changes
Honestly, I think it would be better to simply take TypeScript configs from Vite's own template — https://github.com/vitejs/vite/tree/main/packages/create-vite/template-vue-ts. They even use compositing to make TypeScript check `vite.config.ts` properly.

2024-08-27 10:13 UTC, brawaru commented on apps/app-frontend/tsconfig.json
> +    "moduleResolution": "node",
This should be set to `"bundler"` since we're using Vite.

2024-08-27 10:13 UTC, brawaru commented on apps/app-frontend/tsconfig.json
> +  "include": ["src/**/*.ts", "src/**/*.d.ts", "src/**/*.vue"],
This can be simplified.
```suggestion
  "include": ["src"],
```

2024-09-08 06:46 UTC, closed without merging

2024-09-08 06:46 UTC, ferothefox commented
Succeeded by #2364