Smtp dev setup
modrinth/code pull request #2886
Opened 2024-11-03 09:31 UTC by Erb3

This will help setting up labrinth for local development. You can now use a mock SMTP server such as smtp4dev. The TLS options will stay the same as before if set to `true`, and disabled when `false`.

Depends on https://github.com/modrinth/code/pull/2883

2024-11-23 19:10 UTC, Erb3 commented
Prioritizing this over #2883, making that one a draft and removing dependency on it due to conflicts.

2025-04-21 12:23 UTC, AlexTMjugador requested changes
This PR addresses a real issue and is looking great overall, thank you! I'd like to take stewardship of it and work toward getting it merged soon. @Erb3, could you please update the branch and take a look at the comments below?

2025-04-21 12:23 UTC, AlexTMjugador commented on apps/labrinth/src/auth/email/mod.rs
> +    let port = dotenvy::var("SMTP_PORT")?.parse::<u16>().unwrap_or(25);
Let's change the default value of `SMTP_PORT` to match `lettre`'s SMTP over TLS `SUBMISSIONS_PORT`, which is 465, to minimize changes of production deployments breaking due this new environment variable being unset:

```suggestion
    let port = dotenvy::var("SMTP_PORT")?.parse::<u16>().unwrap_or(465);
```

2025-04-21 12:23 UTC, AlexTMjugador commented on apps/labrinth/src/auth/email/mod.rs
> +        };
Would you be open to extending the range of values accepted by `SMTP_TLS` to include both optional and required STARTTLS? This would provide full coverage of [`lettre`'s `Tls` enum](https://docs.rs/lettre/latest/lettre/transport/smtp/client/enum.Tls.html) and improve compatibility with services like Mailtrap, which rely on STARTTLS for encryption in transport.

I'd like to suggest the following values for `SMTP_TLS`, then: `none`, `opportunistic_starttls`, `required_starttls`, and `tls`.

2025-04-22 08:38 UTC, Erb3 commented
Good catches, I've updated the code. The default port is 465, and can be modified with `SMTP_PORT`. The `SMTP_TLS` now accepts the following values:
- `none`
- `opportunistic_start_tls`
- `requires_start_tls`
- `tls`

If none of these values are supplied to `SMTP_TLS`, it will default to TLS and throw a warning.

I have not tested the code with TLS as I don't have an email server. The `none` option has been tested with smtp4dev, and it works well with the following labrinth configuration:

```env
SMTP_USERNAME=modrinth
SMTP_PASSWORD=frog
SMTP_HOST=localhost
SMTP_PORT=2525
SMTP_TLS=none
```

Thank you for your very friendly review!

2025-04-22 10:32 UTC, AlexTMjugador requested changes
Splendid, thank you for your thoughtful PR and comments!

I've tested this on my end with Mailtrap’s STARTTLS-enabled SMTP development server, and everything worked great. It's also trivially clear that the direct TLS case has to function as expected, so we now have full coverage of all practical SMTP transport layer security protocols.

Would you be up for tweaking one last thing before merging?

2025-04-22 10:32 UTC, AlexTMjugador commented on apps/labrinth/src/lib.rs
> +    failed |= check_var::<bool>("SMTP_TLS");
Now that `SMTP_TLS` accepts a string value, this check should be updated accordingly:

```suggestion
    failed |= check_var::<String>("SMTP_TLS");
```

While this doesn't impact functionality, it gets rid of an incorrect warning during Labrinth startup, which is always a nice improvement.

2025-04-22 11:11 UTC, AlexTMjugador approved these changes

2025-04-22 11:46 UTC, merged